version: '2.1'
services:
  db:
    image: postgres:9.6.1
    environment:
      POSTGRES_USER: "birdie"
      POSTGRES_PASSWORD: "pass"
  scraper:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
