# the database image
db:
  image: "postgres:9.4"
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: kitteh
    POSTGRES_PASSWORD: kitteh
  volumes_from:
    - dbdata

# for persistance of database data
dbdata:
  image: "postgres:9.4"
  volumes:
    - /var/lib/postgres
  command: "true"

# the main image, this is the application
web:
  build: "."
  environment:
    MIX_ENV: "prod"
  ports:
    - "4000:4000"
  links:
    - "db:db"
