version: '2'
services:
  db:
    image: postgres:9.5
    environment:
      POSTGRES_USER: "birdie"
      POSTGRES_PASSWORD: "pass"
  web:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
